# Generated by Django 2.2.6 on 2019-11-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_education_experience_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='facebook',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='github',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='google_plus',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='instagram',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='linkedin',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='social',
            name='twitter',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='youtube',
            field=models.URLField(blank=True, max_length=283, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('Student or Learning', 'Student or Learning'), ('Junior Developer', 'Junior Developer'), ('Senior Developer', 'Senior Developer'), ('Developer', 'Developer'), ('Manager', 'Manager'), ('Instructor or Teacher', 'Instructor or Teacher'), ('Intern', 'Intern'), ('ussiness Man', 'Bussiness Man'), ('Digital Marketer', 'Digital Marketer'), ('Data Scientist', 'Data Scientist'), ('Other', 'Other')], default='Web Developer', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default=1, max_length=10),
        ),
    ]
