# Generated by Django 2.2.6 on 2019-11-18 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20191118_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college',
            field=models.CharField(default='Info Tech', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_currently_studying',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='IFS', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_currently_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
