# Generated by Django 2.2.6 on 2019-11-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20191119_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='is_currently_studying',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
